services:
  - type: web
    name: fox-trading-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build && cp _redirects dist/_redirects
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /auth/callback
        destination: /index.html
      - type: rewrite
        source: /app/*
        destination: /index.html
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /register
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: false
