services:
  - type: web
    name: fox-trading-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
